-- ============================================
-- Migración: Deshabilitar RLS en todas las tablas
-- Fecha: 2026-01-29
-- Motivo: Usuario único, no requiere seguridad RLS
-- ============================================

ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE google_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE segments DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE send_runs DISABLE ROW LEVEL SECURITY;
ALTER TABLE send_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE bounce_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE unsubscribe_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE test_send_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_source_memberships DISABLE ROW LEVEL SECURITY;
